### ISSUE TITLE
KeyError: "No object named 'DeformableDetr' found in 'META_ARCH' registry!"

### ISSUE THREAD

**Issue by eternaldolphin** [facebookresearch/Detic#105]
when I run the "configs/BoxSup-DeformDETR_L_R50_2x.yaml", I meet this error, how to solve it

**Comment by eternaldolphin** [comment]
solve it. There is sys.path.insert(0, 'third_party/Deformable-DETR') in train_net.py, but at first i did not compile the deformablr detr correctly

**Comment by junnnxie** [comment]
Hello, I compiled DeformableDetr according to the installation prompts, but I also encountered a problem like yours. Can you share your solution in detail?
