### ISSUE TITLE
TypeError: 'DefaultCfg' object does not support item assignment

### ISSUE THREAD

**Issue by wkfdb** [facebookresearch/Detic#111]
Thanks for sharing such a great job. Here is some issues I get when i tried to run the baselines of the code.
In detail, I was running train_net.py with config BoxSup-C2_Lbase_CLIP_R5021k_640b64_4x.yaml, and it get errors in building backbone.

File "/root/xxxx/Detic-main/detic/modeling/backbone/timm.py", line 82, in create_timm_resnet
    default_cfgs_resnet['resnet50_in21k']['url'] = \
TypeError: 'DefaultCfg' object does not support item assignment

if seems that the default_cfgs_resnet['resnet50_in21k'] is a DefaultCfg object and it can not directly be assigned as dict object.
Any ideas for fixing that?

**Comment by wkfdb** [comment]
I have solved the problem by reading the source code of timm. I dont know why it changes the datatype of default_cfgs when i import it from the source code. That object in source code is a dict, and when i import it, it becomes DefaultCfg.

**Comment by xihuachen9804** [comment]
> I have solved the problem by reading the source code of timm. I dont know why it changes the datatype of default_cfgs when i import it from the source code. That object in source code is a dict, and when i import it, it becomes DefaultCfg.

Hi, I met the same problem as you, can you tell me the exact solution? Thank you very much!

**Comment by alun011** [comment]
Hello, I have also encountered the same problem. Could you please explain the solution?

**Comment by xihuachen9804** [comment]
> Hello, I have also encountered the same problem. Could you please explain the solution?

Hi, I have solved the problem by changing the version of timm to 0.5.4.

**Comment by alun011** [comment]
I have solved my problem according to your method! Thank you！

**Comment by alun011** [comment]
> > Hello, I have also encountered the same problem. Could you please explain the solution?
> 
> Hi, I have solved the problem by changing the version of timm to 0.5.4.

I have solved my problem according to your method! Thank you！

**Comment by wkfdb** [comment]
> > I have solved the problem by reading the source code of timm. I dont know why it changes the datatype of default_cfgs when i import it from the source code. That object in source code is a dict, and when i import it, it becomes DefaultCfg.
> 
> Hi, I met the same problem as you, can you tell me the exact solution? Thank you very much!


 from timm.models.resnet import default_cfgs as default_cfgs_resnet
By reading the source code I found that timm.models.resnet.default_cfgs is a pre-defined dict object. I dont know why it changes to DefaultCfg object when imported. So I just define default_cfgs_resnet as the same way in source code as follow:
default_cfgs_resnet = {
    # ResNet and Wide ResNet
    'resnet50': _cfg(
        url='https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth',
        interpolation='bicubic', crop_pct=0.95),
}
Then it worked.
