### ISSUE TITLE
KeyError: "No object named 'DeformableDetr' found in 'META_ARCH' registry!"

### ISSUE THREAD

**Issue by junnnxie** [facebookresearch/Detic#114]

**Comment by junnnxie** [comment]
After compiling normally, I later discovered that this was an `import` problem, which I later solved.

**Comment by Xuxiaoxiaohaha** [comment]
> After compiling normally, I later discovered that this was an `import` problem, which I later solved.

Do you remember how to deal with it?

**Comment by Xuxiaoxiaohaha** [comment]
> > After compiling normally, I later discovered that this was an `import` problem, which I later solved.
> 
> Do you remember how to deal with it?

solving it by following step:
add "from models.deformable_detr import DeformableDETR" after the sys.path.insert(0, 'third_party/Deformable-DETR') in train_net.py
