### ISSUE TITLE
How to get inference faster at the expense of something (accuracy, class number, etc..)?

### ISSUE THREAD

**Issue by HiroIshida** [facebookresearch/Detic#12]
I am currently trying to use this software for realtime domain like robotics, where faster inference is often preferred to high accuracy. https://github.com/HiroIshida/detic_ros

**So it would be great if someone share tips or config settings to make get inference faster at the sacrifice of something  (accuracy, class number, etc..).**

A simple attempt to do that end may changing the input image size. However, the inference time varying input image size is like follows, which means input image size is not the primal factor.
300x300 0.19
100x100 0.17
50x50   0.165
(Using Geforce GTX-1080ti and the model is used as same as the demo described in README)

Finally, thank you very much for releasing such a great software.

**Comment by xingyizhou** [comment]
Hi,

  Thank you for the great request. Our main 21K model uses Swin-B backbone, which is inherently not designed for a real-time inference. It is a bit hard to optimize the Swin-B model for real-time usage. We will release smaller models trained on ImageNet-21K for real-time usage. The target timeline is within a month.

  In the meantime, you can try the following (minor) optimizations:
  - set `cfg.MODEL.MASK_ON = False` before creating the model if you don't need segmentation mask.
  - Try fp16 inference.
  - Try batched inference if this is applicable.

**Comment by HiroIshida** [comment]
Thank you very much for your response. I will try your suggestion!

**Comment by xingyizhou** [comment]
Hi @HiroIshida,

  Thank you for your patience. We released a few real-time models [here](https://github.com/facebookresearch/Detic/blob/main/docs/MODEL_ZOO.md#real-time-models).

Best,
Xingyi

**Comment by xingyizhou** [comment]
@Joren-vanGoethem 

   You can do `model = model.half()` and set the image tensor to half before feeding it to the model.

**Comment by HiroIshida** [comment]
@xingyizhou Thank you very much! I'll try soon !!
