### ISSUE TITLE
About preparing COCO data

### ISSUE THREAD

**Issue by VSPW-dataset** [facebookresearch/Detic#20]
when preparing coco caption data, I did 

python tools/get_cc_tags.py --cc_ann datasets/coco/annotations/captions_train2017.json --out_path datasets/coco/captions_train2017_tags_allcaps.json --allcaps --convert_caption

and got 

Traceback (most recent call last):
  File "/data03/jiaxu/open_vocabulary_det/Detic-main/tools/get_cc_tags.py", line 135, in <module>
    id2cat = {x['id']: x for x in cc_data['categories']}
KeyError: 'categories'.

Did I miss something?

**Comment by NickChang97** [comment]
Hi, I excute the same command with you. After using the --cat_path datasets/coco/annotations/instances_val2017.json according to another issue, the KeyError: 'categories' is solved. But I get 
File "tools/get_cc_tags.py", line 153, in <module>
    caption = (' '.join(x['captions'])).lower()
KeyError: 'captions'
Did you solve this, can you provide some help, thanks in advance.
