### ISSUE TITLE
Screenshot source and capability to run on CPU only

### ISSUE THREAD

**Issue by joakimeriksson** [facebookresearch/Detic#26]
I have added a few features to the demo application - one is to enable a screen-shot video source so that it is possible to run on screen as video input. I also added an additional argument for specifying CPU only as I do not have a GPU on my MAC. Is this of interest - should I prepare a PR with this?

Screenshots like this can be run in the demo application:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/599447/154347273-fd430154-7934-40c0-b220-5e4b25d14b11.png">

**Comment by imisra** [comment]
@joakimeriksson This is really cool :) A PR would be nice!

**Comment by joakimeriksson** [comment]
Ok, I did PR #30 now.
