### ISSUE TITLE
how to finetune your model with custom classification data

### ISSUE THREAD

**Issue by feiyilicare** [facebookresearch/Detic#27]
could you provide config file for only use classification data to finetune the model

**Comment by xingyizhou** [comment]
Hi,

  Thank you for your interest. First, please make sure you understand how to prepare custom **detection** datasets (referring to the COCO format and the detectron2 tutorial). 

  The difference between detection data and classification data is we don't have the `annotation` list. However, each item in the `images` list needs to have an additional field `pos_category_ids` of a list of integers. The values in the list are the category ids of the appeared categories. Please see [here](https://github.com/facebookresearch/Detic/blob/main/tools/create_imagenetlvis_json.py#L41) for references. 

Best,
Xingyi

**Comment by xingyizhou** [comment]
Closing due to lack of activities. Feel free to reopen.
