### ISSUE TITLE
Is the number of lvis rare classes 317?

### ISSUE THREAD

**Issue by parang99** [facebookresearch/Detic#29]
Hi @xingyizhou ,

Your arxiv paper mentions that the number of LVIS-base classes is 886. 

When I tested with the lvis_v1_train_cat_info.json and lvis_v1_train.json, the number of common - frequent - rare classes was 461 - 405 - 337.

Also ViLD used 866 base categories. 

I don't know which one is right, between 317 and 337. 

Thanks,
Janet

**Comment by xingyizhou** [comment]
Hi,

  Thank you for catching the typo in the paper! It should be 866 and 337 for base and rare classes, as in the code and the literature. We will update the paper.

Best,
Xingyi

**Comment by parang99** [comment]
Thanks
