### ISSUE TITLE
How are the bbox labels predicted during testing?

### ISSUE THREAD

**Issue by wusize** [facebookresearch/Detic#36]
I am curious about how the bbox labels are predicted since the data are split into base and novel. Taking LVIS as example, when calculating the AP_novel, are the labels obtained by taking the maximum of the 1203 scores of all categories or only  the maximum of the 337 novel categories?

**Comment by xingyizhou** [comment]
Hi,

  Thank you for your question. There is no "maximum of the X classes". We take the top 300 predictions of the **1203** classes. One box can have multiple class labels and different classes are evaluated separately in mAP.

**Comment by wusize** [comment]
Does that mean for each classes, 300 top predictions are taken?

**Comment by xingyizhou** [comment]
No. We take total of 300 predictions for all classes.

**Comment by xingyizhou** [comment]
Closing due to lack of activities. Feel free to reopen.

**Comment by wusize** [comment]
Hi! Another question about the prediction of bbox labels. I find that the classifier predict 80 scores for each proposal when doing inference on COCO dataset. But the open-vocabulary setting only uses 65 out of the 80 categories. So will the top 300 predictions   possibly include labels belonging to the rest 15 categories?
