### ISSUE TITLE
List of the 21K labels

### ISSUE THREAD

**Issue by subhamkhemka** [facebookresearch/Detic#4]
Hi Team,

Thanks for releasing the work and sharing your code!

I would like to get the list of the labels which the model can predict. 
Where can I find this information

Thanks,
Subham

**Comment by BIGBALLON** [comment]
You can find the WordNet IDs of the classes [here](https://storage.googleapis.com/bit_models/imagenet21k_wordnet_lemmas.txt)

**Comment by subhamkhemka** [comment]
@BIGBALLON  thanks for getting back so quickly!

**Comment by xingyizhou** [comment]
Thanks @BIGBALLON for answering. To make it more clear, during inference our model and predict any classes (including labels NOT in the 21K ImageNet classes), just by providing a name in text. See our custom vocabulary example in the readme.

**Comment by subhamkhemka** [comment]
Understood, thanks! @xingyizhou

**Comment by subhamkhemka** [comment]
@xingyizhou, Could you please point me towards the model file which can be used to predict using the 21K labels ?

BUILDIN_CLASSIFIER = {
    'lvis': 'datasets/metadata/lvis_v1_clip_a+cname.npy',
    'objects365': 'datasets/metadata/o365_clip_a+cnamefix.npy',
    'openimages': 'datasets/metadata/oid_clip_a+cname.npy',
    'coco': 'datasets/metadata/coco_clip_a+cname.npy',
}

BUILDIN_METADATA_PATH = {
    'lvis': 'lvis_v1_val',
    'objects365': 'objects365_v2_val',
    'openimages': 'oid_val_expanded',
    'coco': 'coco_2017_val',
}

vocabulary = 'lvis' # change to 'lvis', 'objects365', 'openimages', or 'coco'
metadata = MetadataCatalog.get(BUILDIN_METADATA_PATH[vocabulary])
classifier = BUILDIN_CLASSIFIER[vocabulary]
num_classes = len(metadata.thing_classes)


By choosing from the above vocabulary list I am unable to get len(num_classes) as 21K.
