### ISSUE TITLE
How can I get box_features?

### ISSUE THREAD

**Issue by yoojin9649** [facebookresearch/Detic#41]
Hello. Thanks for sharing your code!

I checked [Colab](https://colab.research.google.com/drive/1QtTW9-ukX2HKZGvt0QvVGqjuqEykoZKI) demo code.

When I run the following code `outputs = predictor(im)` in colab demo, I was able to get box location information(not sure about this expression, `pred_boxes`) from `outputs`.

But, I was wondering how can I get features(`box_features`) for these boxes.

Thanks for reading!

**Comment by xingyizhou** [comment]
You will need to modify the Detic code and add the features to the output. The box features are [here](https://github.com/facebookresearch/Detic/blob/main/detic/modeling/roi_heads/detic_roi_heads.py#L263).

**Comment by yoojin9649** [comment]
Thank you for your prompt response.

I'll give it a try.
