### ISSUE TITLE
Repeat Factor Sampling of open-vocabulary LVIS

### ISSUE THREAD

**Issue by wusize** [facebookresearch/Detic#42]
When training on LVIS with RepeatFactorTrainingSampler, are rare classes taken into account? I think it makes more sense to not consider the rare classes when calculating the repeat factor.

**Comment by xingyizhou** [comment]
No. The RFS factors are always computed on-the-fly based on the current available annotations.

**Comment by wusize** [comment]
OK. Thank you!
