### ISSUE TITLE
How can I get 1280 dimensional box_features?

### ISSUE THREAD

**Issue by yoojin9649** [facebookresearch/Detic#45]
Hello.

I was able to get `box_features` from a [previous question](https://github.com/facebookresearch/Detic/issues/41).

The dimension of these `box_features` was `1024` as shown in the config file in the picture below.

![image](https://user-images.githubusercontent.com/59722489/160786711-f2567c13-19d5-4600-822e-4637bffd7fbd.png)

I'm trying to use this `box_features` in another pre-trained model, but the dimension doesn't match. This is because the dimension of other pre-trained models is `1280`.

I was wondering if I need to re-train the model from scratch to get `box_features` of `1280` dimension or how to get it.

Or, I was wondering if it is a good way to extend the dimension with **Autoencoder** or **PCA** method to convert from 1024 dimension to 1280 dimension.

Thank you for your time to read this question!

**Comment by yoojin9649** [comment]
Thank you for your prompt response!

**Comment by Edwardmark** [comment]
@xingyizhou hi, how to get the box features of 512 dim to calculate similarity with clip text embedding?
