### ISSUE TITLE
can this be migrated to segmentation

### ISSUE THREAD

**Issue by jeannotes** [facebookresearch/Detic#5]
thanks for your code release, you did detection, will segmentation be ok?

**Comment by xingyizhou** [comment]
Hi,

  Thank you for your interest. Our model already includes instance segmentation (see demos in README.md). 

  If you are asking about semantic segmentation, there are already great concurrent works using the CLIP classifier (see [lang-seg](https://github.com/isl-org/lang-seg) and [OpenSeg](https://arxiv.org/abs/2112.12143)). However, it's unclear how to use image-level supervision to help there.

Best,
Xingyi

**Comment by xingyizhou** [comment]
Closing due to lack of activities. Feel free to reopen.
