### ISSUE TITLE
question about best checkpoint during training time

### ISSUE THREAD

**Issue by dneirfi** [facebookresearch/Detic#50]
Hi 
Thank you for sharing your interesting work:)

I have a question about the best checkpoint during training time.
I found that when I trained my custom model to LVIS dataset, model_final.pth is not always the best inference score.
Sometimes other checkpoints like model_0079999.pth are better than final checkpoint. 

Did it occur during the Detic model's training time too? 
And I wonder that you reported model's inference score with model_final checkpoint.

Thanks

**Comment by xingyizhou** [comment]
Hi,

  I haven't looked at the intermediate results. We always report numbers of the final model.

**Comment by dneirfi** [comment]
Thank you for reply!
