### ISSUE TITLE
assert (boxes1[:, 2:] >= boxes1[:, :2]).all() error

### ISSUE THREAD

**Issue by dneirfi** [facebookresearch/Detic#54]
Hi. 
Thanks for sharing your work!

I got "assert (boxes1[:, 2:] >= boxes1[:, :2]).all()" error when I run ovcoco based on deformable detr.
When I searched the error, the error is usually caused by number of classes.

I set num_classes=80 in config file and use  'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json' in fed_loss, zs_weight_path = "datasets/metadata/coco_clip_a+cname.npy"

I found that "enc_outputs_coor_unact" returns inf in tensor. 

Is there any mistakes that I did or any solution to resolve the error?

Thanks.

**Comment by dneirfi** [comment]
I solved the problem!

Thanks.

**Comment by hq-deng** [comment]
Hello, how did you address this problem? Thanks.
