### ISSUE TITLE
Is it possible to fine tune my dataset?

### ISSUE THREAD

**Issue by miladfa7** [facebookresearch/Detic#6]
thanks for your code release, Is it possible to fine tune my dataset?

**Comment by xingyizhou** [comment]
Thank you for your interest. It is definitely possible. Just follow the [detectron2 instruction](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) about custom datasets. You may also need to generate the CLIP embeddings of your dataset by referring to [here](https://github.com/facebookresearch/Detic/tree/main/datasets#metadata).

**Comment by xingyizhou** [comment]
Closing due to lack of activities. Feel free to reopen.
