### ISSUE TITLE
torchscipt export error 

### ISSUE THREAD

**Issue by anshudaur** [facebookresearch/Detic#63]
Hi,

Thank you for the great work.
I am exporting torch script model but during inference I run into shapes error for model corresponding to the config : "Detic_LI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.yaml"

**export script example :**  

    # Prepare inputs 

    im = cv2.imread('input.jpg')
    image = aug.get_transform(im).apply_image(im)
    image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))
    inputs = [{"image": image}]

    ## Export to torchscipt
    if isinstance(model, GeneralizedRCNN):
        def inference(model, inputs):
            # use do_postprocess=False so it returns ROI mask
            inst = model.inference(inputs, do_postprocess=False)[0]
            return [{"instances": inst}]
    else:
        inference = None

    traceable_model = TracingAdapter(model, inputs, inference)
    traceable_model.eval()
    _# 1. option : pass image array as a tuple_
    ts_model = torch.jit.trace(traceable_model, (image,))
    _# or 2nd option_ 
    # ts_model = torch.jit.trace(traceable_model, image, strict=False)
    d = {"shape": image.shape}
    extra_files = {'exported_config.txt': json.dumps(d)}

    with open("models/detic_model_2.ts", "wb") as f:
        torch.jit.save(ts_model, f)

**Comment by anshudaur** [comment]
export_model script adapted from electron gives shape error : 

File ~/anaconda3/envs/detectron/lib/python3.9/site-packages/torch/nn/modules/module.py:1051, in Module._call_impl(self, *input, **kwargs)
   1047 # If we don't have any hooks, we want to skip the rest of the logic in
   1048 # this function, and just call forward.
   1049 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051     return forward_call(*input, **kwargs)
   1052 # Do not call functions when jit is used
   1053 full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/detectron2/export/flatten.py", line 29, in forward
    batched_imgs = torch.unsqueeze_(_13, 0)
    x0 = torch.contiguous(batched_imgs)
    _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, = (_3).forward(x0, )
                                                                                            ~~~~~~~~~~~ <--- HERE
    _31 = (_2).forward(_14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, )
    _32, _33, = _31
  File "code/__torch__/detectron2/modeling/backbone/fpn.py", line 23, in forward
    _5 = self.fpn_output5
    _6 = self.fpn_lateral5
    _7, _8, _9, = (self.bottom_up).forward(x, )
                   ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _10 = (_6).forward(_7, )
    _11 = (_5).forward(_10, )
  File "code/__torch__/detic/modeling/backbone/swintransformer.py", line 36, in forward
    _18 = int(W)
    input = torch.transpose(torch.flatten(_8, 2), 1, 2)
    _19 = (_6).forward(H, W, (_7).forward(input, ), _13, _18, _12, _17, _11, _16, _10, _15, _9, _14, )
           ~~~~~~~~~~~ <--- HERE
    _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, = _19
    _35 = (_5).forward(_20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, )
  File "code/__torch__/detic/modeling/backbone/swintransformer.py", line 159, in forward
    mask = torch.masked_fill(_199, torch.eq(attn_mask, 0), 0.)
    _200 = (_142).forward(argument_3, H, W, argument_4, argument_5, argument_6, argument_7, )
    _201 = (_141).forward(_200, H, W, argument_8, argument_9, mask, argument_10, argument_11, )
            ~~~~~~~~~~~~~ <--- HERE
    _202 = (_140).forward(_201, H, W, argument_12, argument_13, )
    H0 = torch.floor_divide(torch.add(H, CONSTANTS.c12), CONSTANTS.c13)
  File "code/__torch__/detic/modeling/backbone/swintransformer/___torch_mangle_28.py", line 59, in forward
    x_windows = torch.view(torch.contiguous(_25), [-1, 7, 7, _20])
    x2 = torch.view(x_windows, [-1, 49, _9])
    windows = torch.view((_3).forward(x2, mask, ), [-1, 7, 7, _8])
                          ~~~~~~~~~~~ <--- HERE
    _26 = torch.floor_divide(H0, CONSTANTS.c11)
    _27 = int(_26)
  File "code/__torch__/detic/modeling/backbone/swintransformer/___torch_mangle_21.py", line 54, in forward
    _23 = int(other)
    _24 = [int(torch.floor_divide(B_, other)), _23, 4, _13, _12]
    _25 = torch.view(attn0, _24)
          ~~~~~~~~~~ <--- HERE
    _26 = torch.unsqueeze(torch.unsqueeze(mask, 1), 0)
    attn1 = torch.add(_25, _26)


/Detic/export_model.py(135): export_tracing
/Detic/export_model.py(235): <module>
RuntimeError: shape '[0, 1131, 4, 49, 49]' is invalid for input of size 3976056

**Comment by xingyizhou** [comment]
Hi,

  Unfortunately I have minimal experience in exporting models. Can you check the detectron2 instructions [here](https://github.com/facebookresearch/detectron2/tree/main/tools/deploy) and make sure you can export other detectron2 models? The detectron2 issue might be a better place to ask about this.

Best,
Xingyi

**Comment by anshudaur** [comment]
@xingyizhou Yes, I was able to export Mask RCNN model as provided in the examples.

**Comment by anshudaur** [comment]
Closing this, as  nms operation results to a variable sized output which cannot be exported, so you can comment following in third_party projects -> center.py file :
 boxlists = self.nms_and_topK(
                boxlists, nms=not self.not_nms
            )

while also commenting ScaleGradient line in custom_rcnn.py

box_features = _ScaleGradient.apply(box_features, 1.0 / self.num_cascade_stages)

Exporting to onnx and torchscript with tracing using detectron2's [export_model](https://github.com/facebookresearch/detectron2/blob/bbdee4cf6bc100fedad7cfad3225bb1da12fa175/tools/deploy/export_model.py) script works.

**Comment by chaos1992** [comment]
@anshudaur hi, have you exported detic to onnx or other formats successfully？If yes, can you share your code?

**Comment by anshudaur** [comment]
@amirhmk The author has provided this metadata files here : https://github.com/facebookresearch/Detic/issues/77#issuecomment-1250412579

**Comment by anshudaur** [comment]
@chaos1992 you can refer to detectron's export model script for this.  Please refer here : https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/README.md?plain=1
