### ISSUE TITLE
Can I get extract just the prediction labels and the confidence level?

### ISSUE THREAD

**Issue by texturejc** [facebookresearch/Detic#7]
HI, thanks for making Detic available; there's some fantastic functionality in here. 

My issue is quite mundane: How can I get the `predictor` function to output the prediction classes as text strings with an associated confidence level? I'd like to iterate across a large number of images and record the results in a pandas dataframe or similar. Having them overlaid on an image is less useful for this.

Thanks!

**Comment by xingyizhou** [comment]
Hi, 
  Thank you for your interest. I have updated the examples to get detailed outputs in the [colab](https://colab.research.google.com/drive/1QtTW9-ukX2HKZGvt0QvVGqjuqEykoZKI) (last block). The outputs are stored in `outputs["instances"]`. The format details can be found in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format.

**Comment by AlexanderKozhevin** [comment]
Here is a list of labels
https://gist.github.com/AlexanderKozhevin/36eac63dbb57590658d2e3a8f9e9c98f

**Comment by AlexanderKozhevin** [comment]
@xingyizhou Sorry for stupid question - so lvis gives 1203 classes.
But in configuration - Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.yaml I can see 22047.
How can we use all 22047 classes?

**Comment by xingyizhou** [comment]
Answered [here](https://github.com/facebookresearch/Detic/issues/15).
