### ISSUE TITLE
How to get object features from each detection.

### ISSUE THREAD

**Issue by RaiAnant** [facebookresearch/Detic#71]
Is there a convenient way to get the object features used for classification (clip embeddings), as outputs along with the bounding boxes?

**Comment by xingyizhou** [comment]
Hi,

  The features are [here](https://github.com/facebookresearch/Detic/blob/main/detic/modeling/roi_heads/zero_shot_classifier.py#L75). It may need some changes in code to pass it to the outputs.

Best,
Xingyi

**Comment by RaiAnant** [comment]
Thanks. I am trying to make changes to the code to pass it along with other outputs like bounding boxes and class predictions. But I am unsure of one section of the code. In the [inference mode, inside detic_roi_heads.py](https://github.com/facebookresearch/Detic/blob/46f8317a0688b4b94e85816b5839a1dbca26d1e0/detic/modeling/roi_heads/detic_roi_heads.py#L144), I am not clear what is really happening. While having outputs from different stages (head_outputs), the predictor, predictions and proposals are only considered from the finals stage (head_outputs[-1]). Would be glad if you can clarify that part. Thanks again!
