### ISSUE TITLE
No such file or directory: 'datasets/metadata/lvis-21k_clip_a+cname.npy'

### ISSUE THREAD

**Issue by xing0047** [facebookresearch/Detic#77]
Thanks for open-sourcing the great work of Detic for the community!

I encountered the problem when trying to reproduce the result of [cross-dataset evaluation](https://github.com/facebookresearch/Detic/blob/46f8317a0688b4b94e85816b5839a1dbca26d1e0/docs/MODEL_ZOO.md#cross-dataset-evaluation) in [MODEL_ZOO.md](https://github.com/facebookresearch/Detic/blob/46f8317a0688b4b94e85816b5839a1dbca26d1e0/docs/MODEL_ZOO.md)
```
python train_net.py --num-gpus 2 --config-file configs/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.yaml --eval-only DATASETS.TEST "('objects365_v2_val',)" MODEL.RESET_CLS_TESTS True MODEL.TEST_CLASSIFIERS "('datasets/metadata/o365_clip_a+cnamefix.npy',)" MODEL.TEST_NUM_CLASSES "(365,)" MODEL.MASK_ON False MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth
```
The reported issue is as follows:
```
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/metadata/lvis-21k_clip_a+cname.npy'
```
It is reported that there should be a pre-computed embedding of lvis-21k using CLIP. The corresponding instruction is under [Metadata](https://github.com/facebookresearch/Detic/tree/46f8317a0688b4b94e85816b5839a1dbca26d1e0/datasets#metadata).
```
python tools/dump_clip_features.py --ann datasets/lvis/lvis_v1_val_lvis-21k.json --out_path datasets/metadata/lvis-21k_clip_a+cname.npy
```
It seems that the `lvis_v1_val_lvis-21k.json` could be generated by running `python tools/create_lvis_21k.py` with replacing the default value of `lvis_path` with `datasets/lvis/lvis_v1_val.json`. For now I am facing the same issue as in #48. Is there any other way to get access to the file `lvis_v1_val_lvis-21k.json` instead of building it up from scratch? Thanks.

**Comment by xingyizhou** [comment]
Hi,

  Sorry for the inconvenience and my late reply. You can find the file [here](https://drive.google.com/file/d/1aw9-4veJkfUJ1gtBNPtFQbxaBJITSOxJ/view?usp=sharing).

Best,
Xingyi

**Comment by xing0047** [comment]
Thanks for your help!

**Comment by ysysys666** [comment]
This link cannot be opened, could you please send it again, thank you very much @xingyizhou @xing0047
