### ISSUE TITLE
CPU Training is not clarified

### ISSUE THREAD

**Issue by Frozander** [facebookresearch/Detic#8]
This seems a bit nitpicky since one can google around to find an answer but here it goes.

README states this model does not require GPU but when GPU in the notebook kernel is disabled detectron2 gives a cuda error if the notebook is not modified, while creating `DefaultPredictor`.

```python
cfg.MODEL.DEVICE='cpu'
```

needs to be added to fix this issue if there is no GPU present.

**Comment by xingyizhou** [comment]
Hi,
  Thank you for your interest. By "no GPU needed" we mean no local GPU is needed on your machine. By default, we use the free GPU in Colab for inference. As you pointed out, our model can run on CPU by adding `cfg.MODEL.DEVICE='cpu'`.

**Comment by xingyizhou** [comment]
Thank you for raising up this issue. We have added instructions to use cpu-only mode in colab.

**Comment by Frozander** [comment]
Thanks!
